[package]
name = "logica"
version = "0.1.0"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen = "0.1.8"
cpal = "0.13.3"
rand = "0.8.3"
anyhow = "1.0.40"
eframe = "0.12.0"
im-native-dialog = "0.2.0"
