[package]
name = "logica"
version = "0.1.0"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
cpal = "0.15.2"
log = "0.4.17"
fern = "0.6.2"
chrono = "0.4.24"
eframe = "0.22.0"
egui_dock = "0.6.1"
