[package]
name = "logica"
version = "0.1.0"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
fern = "0.6.1"
anyhow = "1.0.68"
chrono = "0.4.23"
eframe = "0.20.1"
egui_node_graph = "0.4.0"
egui_dock = "0.3.1"
cpal = "0.14.2"
