[package]
name = "logica"
version = "0.1.0"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [ "crates/*" ]

[dependencies]
vst = "0.3"
log = "0.4.17"
simple-logging = "2.0.2"
dlopen = "0.1.8"
anyhow = "1.0.58"
egui = "0.16.1"
egui_glium = "0.16.0"
egui-winit = "0.16.0"
epi = "0.16.0"
winapi = "0.3.9"
winit = "0.26.1"
glium = "0.31.0"
bincode = "1.3.3"
serde = "1.0.137"
im-native-dialog = "0.3.0"
logica_bridge = { path = "crates/logica_bridge" }

[lib]
name = "logica"
crate-type = ["cdylib"]
