[package]
name = "logica"
version = "0.1.0"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen = "0.1.8"
anyhow = "1.0.40"
eframe = "0.15.0"
im-native-dialog = "0.2.0"
vst = "0.2"

[lib]
name = "logica"
crate-type = ["cdylib"]
